version: '2'

services:
    drupal:
        image: drupal
        ports:
            - 8080:80
        depends_on:
            - database
        volumes:
            - /var/www/html/modules
            - /var/www/html/profiles
            - /var/www/html/themes
            - /var/www/html/sites
    database:
        image: postgres
        environment:
            POSTGRES_DB: drupal
            POSTGRES_USER: user
            POSTGRES_PASSWORD: pass